from setuptools import setup, find_packages

setup(
    name='africanspending',
    version='1.0',
    description="Mapping the money, across the African continent",
    long_description='',
    classifiers=[],
    keywords='',
    author='Code for Africa',
    author_email='tech@codeforafrica.org',
    url='https://www.africanspending.org',
    license='MIT',
    packages=find_packages(exclude=['ez_setup', 'examples', 'tests']),
    namespace_packages=[],
    include_package_data=False,
    zip_safe=False,
    install_requires=[
        "Flask==0.10.1",
        "Flask-Assets==0.10",
        "Flask-FlatPages==0.5",
        "Flask-Script==2.0.5",
        "Frozen-Flask==0.11",
        "PyYAML>=4.2b1",
        "Unidecode==0.04.16",
        "awscli==1.4.4",
        "cssmin==0.2.0",
        "python-dateutil==2.2",
        "python-slugify==0.0.9",
        "requests==2.4.3",
        "gunicorn>=19.0"
    ],
    tests_require=[],
    entry_points="",
)
